login: &login
  adapter: mysql2
  pool: 5
  username: root
  password: 123

development:
  <<: *login
  database: parkshop_development

test:
  <<: *login
  database: parkshop_test

production:
  <<: *login
  database: parkshop_production

