login: &login
  #adapter: mysql2
  adapter: postgresql
  pool: 5
  username: alex
  password: 123

development:
  <<: *login
  database: parkshop_development

test:
  <<: *login
  database: parkshop_test

production:
  <<: *login
  database: parkshop_production

