login: &login
  adapter: postgresql
  pool: 5
  username: ubuntu
  password: 

development:
  <<: *login
  database: parkshop_development

test:
  <<: *login
  database: parkshop_test

production:
  <<: *login
  database: parkshop_production

