login: &login
  #adapter: mysql2
  adapter: postgresql
  pool: 5
  username: alex
  password: 123

development:
  <<: *login
  database: parkshop_development_fauna

test:
  <<: *login
  database: parkshop_test_fauna

production:
  <<: *login
  database: parkshop_production_faune

